### ISSUE TITLE
Unsupported ioctl: cmd=0xffffffff80046601 

### ISSUE THREAD

**Issue by streamnsight** [resin-io-projects/armv7hf-debian-qemu#8]
trying to cross compile opencv for arm and this image works great, but on the 
`make package` phase, I'm getting lots of 

`Unsupported ioctl: cmd=0xffffffff80046601`

Do you know what this is about?
How could I fix this?
thanks

**Comment by petrosagg** [comment]
This is the ioctl for extended attributes and the qemu version bundled in this image doesn't support it.

Support for those has been added to the upcoming qemu v2.8.0 release https://github.com/qemu/qemu/commit/6080723102d1ad3b553769834d6a23e3f3d8250f

If your build does not require extended attributes it is safe to ignore. Otherwise you could backport the commit I referenced (should apply cleanly) and then it should work fine.

**Comment by streamnsight** [comment]
Thanks for the very quick reply.
I am not sure how I would check if the build requires extended attributes or not. All I see at this point is that I get a couple hundreds of those error messages.

As far as patching, do you mean patching https://github.com/resin-io/qemu with QEMU_EXECVE and rebuilding statically? to put in this image, right?

Thanks

**Comment by petrosagg** [comment]
Usually extended attributes are not required because there are filesystems that don't support them or don't have them enabled. The only reason you see a warning is that QEMU sees an unknown IOCTL and doesn't know if it's harmless or not.

For patching you can cherry-pick the commit I referenced on top of this tag https://github.com/resin-io/qemu/tree/v2.5.0-resin-rc3, which is the source of the binary in this repo, then do a static build and put the result in this image.

**Comment by streamnsight** [comment]
Ok I'll try that. thanks
